---
- hosts: web
  tasks:
  - name: Install apache2 server
    apt: 
      name: apache2
  - name: Start server
    service: name=apache2 state=started
  - name: Install index.jtml
    template:
      src: templates/index.html
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: '0664'